/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aureligiuliagarathread;

/**
 *
 * @author aureli.giulia
 */
public class FrmInformazioni extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInformazioni.class.getName());

    /**
     * Creates new form FrmInformazioni
     */
    public FrmInformazioni() {
        initComponents();
        lblConcorrente1.setForeground(java.awt.Color.decode("#f04ae2"));
        lblConcorrente2.setForeground(java.awt.Color.decode("#e8adff"));
        lblConcorrente3.setForeground(java.awt.Color.decode("#4ad7f0"));
        lblConcorrente4.setForeground(java.awt.Color.decode("#2d2e2e"));
        lblConcorrente5.setForeground(java.awt.Color.decode("#e6d21e"));
        lblConcorrente6.setForeground(java.awt.Color.decode("#f5540a"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSchermata = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlTesto = new javax.swing.JPanel();
        lblTesto2 = new javax.swing.JLabel();
        lblTesto1 = new javax.swing.JLabel();
        lblConcorrente1 = new javax.swing.JLabel();
        lblConcorrente2 = new javax.swing.JLabel();
        lblConcorrente3 = new javax.swing.JLabel();
        lblConcorrente4 = new javax.swing.JLabel();
        lblConcorrente5 = new javax.swing.JLabel();
        lblConcorrente6 = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informazioni");

        pnlSchermata.setBackground(new java.awt.Color(51, 51, 51));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/alien_stage_logo-removebg-preview.png"))); // NOI18N

        lblTesto2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTesto2.setText("Ci sono 6 personaggi:");

        lblTesto1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTesto1.setText("Alien stage è un torneo tra cantanti che prevede 5 incontri a eliminazione diretta. ");

        lblConcorrente1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente1.setText("Mizi");

        lblConcorrente2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente2.setText("Sua");

        lblConcorrente3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente3.setText("Till");

        lblConcorrente4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente4.setText("Ivan");

        lblConcorrente5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente5.setText("Luka");

        lblConcorrente6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcorrente6.setText("Hyuna");

        javax.swing.GroupLayout pnlTestoLayout = new javax.swing.GroupLayout(pnlTesto);
        pnlTesto.setLayout(pnlTestoLayout);
        pnlTestoLayout.setHorizontalGroup(
            pnlTestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTesto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTesto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConcorrente6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTestoLayout.setVerticalGroup(
            pnlTestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConcorrente1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConcorrente2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConcorrente3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConcorrente4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConcorrente5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConcorrente6)
                .addContainerGap())
        );

        btnChiudi.setBackground(new java.awt.Color(0, 0, 0));
        btnChiudi.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("CHIUDI");
        btnChiudi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiudi.setFocusPainted(false);
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSchermataLayout = new javax.swing.GroupLayout(pnlSchermata);
        pnlSchermata.setLayout(pnlSchermataLayout);
        pnlSchermataLayout.setHorizontalGroup(
            pnlSchermataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSchermataLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlTesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(pnlSchermataLayout.createSequentialGroup()
                .addGroup(pnlSchermataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSchermataLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblLogo))
                    .addGroup(pnlSchermataLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnChiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSchermataLayout.setVerticalGroup(
            pnlSchermataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSchermataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLogo)
                .addGap(45, 45, 45)
                .addComponent(pnlTesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnChiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSchermata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSchermata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        //chiudo il form
        this.dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInformazioni().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JLabel lblConcorrente1;
    private javax.swing.JLabel lblConcorrente2;
    private javax.swing.JLabel lblConcorrente3;
    private javax.swing.JLabel lblConcorrente4;
    private javax.swing.JLabel lblConcorrente5;
    private javax.swing.JLabel lblConcorrente6;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTesto1;
    private javax.swing.JLabel lblTesto2;
    private javax.swing.JPanel pnlSchermata;
    private javax.swing.JPanel pnlTesto;
    // End of variables declaration//GEN-END:variables
}
