/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aureligiuliagarathread;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author utente
 */
public class FrmStage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStage.class.getName());
    private MusicaSottofondo musica;
    private boolean musicaMutata;
    /**
     * Creates new form FrmStage
     */
    public FrmStage() {
        initComponents();
        this.setLocationRelativeTo(null);
        //creazione torneo
        GestioneTorneo.nuovoTorneo();
        //creazione round 1
        GestioneRound.azzeraRound();
        GestioneRound.nuovoRound(pb1, pb2);
        //scrittura dati iniziali
        ScriviConcorrenti();
        scriviRound();
        //creazione coda musica
        GestioneMusica.mischiaCanzoni();
        musicaMutata = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnProssimoRound = new javax.swing.JButton();
        btnAvviaRound = new javax.swing.JButton();
        pnlStage = new javax.swing.JPanel();
        pb2 = new javax.swing.JProgressBar();
        pb1 = new javax.swing.JProgressBar();
        lblConcorrente1 = new javax.swing.JLabel();
        lblConcorrente2 = new javax.swing.JLabel();
        lblIconaConcorrente1 = new javax.swing.JLabel();
        lblIconaConcorrente2 = new javax.swing.JLabel();
        lblNRound = new javax.swing.JLabel();
        btnMutaMusica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stage");
        setBackground(new java.awt.Color(204, 204, 204));
        setName("frmStage"); // NOI18N

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenu.setMinimumSize(new java.awt.Dimension(699, 70));

        btnProssimoRound.setBackground(new java.awt.Color(0, 0, 0));
        btnProssimoRound.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnProssimoRound.setForeground(new java.awt.Color(255, 255, 255));
        btnProssimoRound.setText("PROSSIMO ROUND");
        btnProssimoRound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnProssimoRound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProssimoRound.setEnabled(false);
        btnProssimoRound.setFocusPainted(false);
        btnProssimoRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProssimoRoundActionPerformed(evt);
            }
        });

        btnAvviaRound.setBackground(new java.awt.Color(0, 0, 0));
        btnAvviaRound.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAvviaRound.setForeground(new java.awt.Color(255, 255, 255));
        btnAvviaRound.setText("AVVIA ");
        btnAvviaRound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnAvviaRound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvviaRound.setFocusPainted(false);
        btnAvviaRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaRoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAvviaRound, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProssimoRound, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProssimoRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvviaRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pnlStage.setBackground(new java.awt.Color(153, 153, 255));
        pnlStage.setMaximumSize(new java.awt.Dimension(400, 700));

        pb2.setForeground(new java.awt.Color(255, 51, 0));

        lblConcorrente1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblConcorrente1.setText("nome 1");

        lblConcorrente2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblConcorrente2.setText("nome 2");

        lblNRound.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNRound.setText("──── round - ────");

        btnMutaMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMutaMusica.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMutaMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMutaMusica.setText("🔇");
        btnMutaMusica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnMutaMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMutaMusica.setEnabled(false);
        btnMutaMusica.setFocusPainted(false);
        btnMutaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutaMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStageLayout = new javax.swing.GroupLayout(pnlStage);
        pnlStage.setLayout(pnlStageLayout);
        pnlStageLayout.setHorizontalGroup(
            pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStageLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblIconaConcorrente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconaConcorrente2)
                .addGap(107, 107, 107))
            .addGroup(pnlStageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStageLayout.createSequentialGroup()
                        .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStageLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblConcorrente1)
                                .addGap(332, 332, 332)
                                .addComponent(lblConcorrente2))
                            .addGroup(pnlStageLayout.createSequentialGroup()
                                .addComponent(btnMutaMusica)
                                .addGap(176, 176, 176)
                                .addComponent(lblNRound)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlStageLayout.createSequentialGroup()
                        .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        pnlStageLayout.setVerticalGroup(
            pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNRound)
                    .addComponent(btnMutaMusica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcorrente1)
                    .addComponent(lblConcorrente2))
                .addGap(23, 23, 23)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconaConcorrente2)
                    .addComponent(lblIconaConcorrente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProssimoRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProssimoRoundActionPerformed
        if (musica != null) musica.stop();
        GestioneTorneo.getTorneo().registraVincitore(GestioneRound.getVincitoreRound());
        if(!GestioneRound.nuovoRound(pb1, pb2)){
            FrmVincitore frmVincitore = new FrmVincitore();
            frmVincitore.setVisible(true);
            this.dispose();
        }
        else{
            ScriviConcorrenti();
            pb1.setValue(0);
            pb2.setValue(0);
            btnAvviaRound.setEnabled(true);
            btnProssimoRound.setEnabled(false);
            btnMutaMusica.setEnabled(false);
            if(GestioneRound.getNRound() == 5) btnProssimoRound.setText("VEDI VINCITORE");
        }
        scriviRound();
    }//GEN-LAST:event_btnProssimoRoundActionPerformed

    private void btnAvviaRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaRoundActionPerformed
        GestioneRound.avviaRound();
        musica = new MusicaSottofondo(GestioneMusica.cambiaCanzone());
        musica.start();
        if(musicaMutata)musica.setVolume(-80);
        else musica.setVolume(-20);

        btnAvviaRound.setEnabled(false);
        btnProssimoRound.setEnabled(false);
        btnMutaMusica.setEnabled(true);
        Thread t = new Thread(() -> {
            while (!GestioneRound.getRound().isFinito()) {
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {}
            }
            javax.swing.SwingUtilities.invokeLater(() -> {
                btnProssimoRound.setEnabled(true);
                
                JOptionPane.showMessageDialog(this, "Round finito! \n" + GestioneRound.getVincitoreRound() + " ha vinto.");
            });
        });
        t.start();
    }//GEN-LAST:event_btnAvviaRoundActionPerformed

    private void btnMutaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutaMusicaActionPerformed
        if(musicaMutata){
            musica.setVolume(-20);
            btnMutaMusica.setText("🔇");
            musicaMutata = false;
        }
        else{
            musica.setVolume(-80);
            btnMutaMusica.setText("🔊");
            musicaMutata = true;
        }
    }//GEN-LAST:event_btnMutaMusicaActionPerformed

    /**
     * Metodo che aggiorna il label round
     */
    public void scriviRound(){
        if(GestioneRound.getNRound() == 5)lblNRound.setText("──── Finale ────");
        else if(GestioneRound.getNRound() == 4)lblNRound.setText("──── Semi Finale ────");
        else if(GestioneRound.getNRound() < 4) lblNRound.setText("──── Round " + GestioneRound.getNRound() +" ────"); 
    }
    
    /**
     * Metodo che aggiorna i componenti in base ai concorrenti
     */
    public void ScriviConcorrenti(){
        lblConcorrente1.setText(GestioneRound.getConcorrentiAttuali()[0].getNome());
        lblConcorrente2.setText(GestioneRound.getConcorrentiAttuali()[1].getNome());
        pb1.setForeground(GestioneRound.getConcorrentiAttuali()[0].getColore());
        pb2.setForeground(GestioneRound.getConcorrentiAttuali()[1].getColore());
        lblIconaConcorrente1.setIcon(GestioneRound.getConcorrentiAttuali()[0].getIcona());
        lblIconaConcorrente2.setIcon(GestioneRound.getConcorrentiAttuali()[1].getIcona());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvviaRound;
    private javax.swing.JButton btnMutaMusica;
    private javax.swing.JButton btnProssimoRound;
    private javax.swing.JLabel lblConcorrente1;
    private javax.swing.JLabel lblConcorrente2;
    private javax.swing.JLabel lblIconaConcorrente1;
    private javax.swing.JLabel lblIconaConcorrente2;
    private javax.swing.JLabel lblNRound;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlStage;
    // End of variables declaration//GEN-END:variables
}
