/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aureligiuliagarathread;

/**
 *
 * @author utente
 */
public class FrmSchermataIniziale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSchermataIniziale.class.getName());
    private MusicaSottofondo musica; //variabile per la musica
    private boolean musicaMutata; // variabile per vedere se la musica e' mutata
    /**
     * Creates new form SchermataIniziale
     */
    public FrmSchermataIniziale() {
        initComponents();
        // Avvia la musica di sottofondo appena parte la finestra
        musica = new MusicaSottofondo("/suoni/Black_Sorrow.wav");
        musica.start();
        //riduzione del volume
        musica.setVolume(-20);
        musicaMutata = false;
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        btnAvvia = new javax.swing.JButton();
        btnMutaMusica = new javax.swing.JButton();
        btnInformazioni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schermata iniziale");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblTitolo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(153, 255, 255));
        lblTitolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/alien_stage_logo-removebg-preview.png"))); // NOI18N

        btnAvvia.setBackground(new java.awt.Color(0, 0, 0));
        btnAvvia.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAvvia.setForeground(new java.awt.Color(255, 255, 255));
        btnAvvia.setText("AVVIA");
        btnAvvia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnAvvia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvvia.setFocusPainted(false);
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        btnMutaMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMutaMusica.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMutaMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMutaMusica.setText("🔇");
        btnMutaMusica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnMutaMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMutaMusica.setFocusPainted(false);
        btnMutaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutaMusicaActionPerformed(evt);
            }
        });

        btnInformazioni.setBackground(new java.awt.Color(0, 0, 0));
        btnInformazioni.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnInformazioni.setForeground(new java.awt.Color(255, 255, 255));
        btnInformazioni.setText("?");
        btnInformazioni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnInformazioni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformazioni.setFocusPainted(false);
        btnInformazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformazioniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMutaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnInformazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitolo))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvvia)
                    .addComponent(btnMutaMusica)
                    .addComponent(btnInformazioni))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        //la musica viene fermata
        if (musica != null) musica.stop();
        FrmStage frmStage = new FrmStage();
        frmStage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnMutaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutaMusicaActionPerformed
        //controllo per vedere se la musica e' mutata
        if(musicaMutata){
            //alza ill volume
            musica.setVolume(-20);
            btnMutaMusica.setText("🔇");
            musicaMutata = false;
        }
        else{
            //muta la musica
            musica.setVolume(-80);
            btnMutaMusica.setText("🔊");
            musicaMutata = true;
        }
    }//GEN-LAST:event_btnMutaMusicaActionPerformed

    private void btnInformazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformazioniActionPerformed
        //apro il form informazioni
        FrmInformazioni frmInformazioni = new FrmInformazioni();
        frmInformazioni.setVisible(true);
    }//GEN-LAST:event_btnInformazioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSchermataIniziale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnInformazioni;
    private javax.swing.JButton btnMutaMusica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
