/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aureligiuliagarathread;

import java.awt.BorderLayout;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author utente
 */
public class FrmStage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmStage.class.getName());
    private MusicaSottofondo musica;
    private boolean musicaMutata;
    private Queue<ImageIcon> sfondi;
    /**
     * Creates new form FrmStage
     */
    public FrmStage() {
        initComponents();
        this.setLocationRelativeTo(null);
        //creazione torneo
        GestioneTorneo.nuovoTorneo();
        //creazione round 1
        GestioneRound.azzeraRound();
        GestioneRound.nuovoRound(pb1, pb2);
        //scrittura dati iniziali
        ScriviConcorrenti();
        scriviRound();
        //creazione coda musica
        GestioneMusica.mischiaCanzoni();
        musicaMutata = false;
        //creazione sfondi
        sfondi = new LinkedList<>(getListaSfondi());
        lblSfondo.setIcon(sfondi.poll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnProssimoRound = new javax.swing.JButton();
        btnAvviaRound = new javax.swing.JButton();
        pnlStage = new javax.swing.JPanel();
        pb2 = new javax.swing.JProgressBar();
        pb1 = new javax.swing.JProgressBar();
        pnlConcorrente1 = new javax.swing.JPanel();
        lblIconaConcorrente1 = new javax.swing.JLabel();
        lblConcorrente1 = new javax.swing.JLabel();
        pnlConcorrente2 = new javax.swing.JPanel();
        lblIconaConcorrente2 = new javax.swing.JLabel();
        lblConcorrente2 = new javax.swing.JLabel();
        pnlRound = new javax.swing.JPanel();
        pnlMenuSuperiore = new javax.swing.JPanel();
        lblNRound = new javax.swing.JLabel();
        btnMutaMusica = new javax.swing.JButton();
        lblSfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stage");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(701, 520));
        setName("frmStage"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenu.setMinimumSize(new java.awt.Dimension(701, 85));
        pnlMenu.setPreferredSize(new java.awt.Dimension(701, 90));

        btnProssimoRound.setBackground(new java.awt.Color(0, 0, 0));
        btnProssimoRound.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnProssimoRound.setForeground(new java.awt.Color(255, 255, 255));
        btnProssimoRound.setText("PROSSIMO ROUND");
        btnProssimoRound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnProssimoRound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProssimoRound.setEnabled(false);
        btnProssimoRound.setFocusPainted(false);
        btnProssimoRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProssimoRoundActionPerformed(evt);
            }
        });

        btnAvviaRound.setBackground(new java.awt.Color(0, 0, 0));
        btnAvviaRound.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAvviaRound.setForeground(new java.awt.Color(255, 255, 255));
        btnAvviaRound.setText("AVVIA ");
        btnAvviaRound.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnAvviaRound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvviaRound.setFocusPainted(false);
        btnAvviaRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaRoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAvviaRound, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnProssimoRound, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProssimoRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvviaRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu);
        pnlMenu.setBounds(0, 410, 701, 100);

        pnlStage.setBackground(new java.awt.Color(153, 153, 255));
        pnlStage.setMaximumSize(new java.awt.Dimension(400, 700));
        pnlStage.setOpaque(false);
        pnlStage.setPreferredSize(new java.awt.Dimension(701, 369));

        pb2.setForeground(new java.awt.Color(255, 51, 0));

        pnlConcorrente1.setBackground(new java.awt.Color(51, 255, 255));
        pnlConcorrente1.setOpaque(false);
        pnlConcorrente1.setLayout(new java.awt.BorderLayout());

        lblIconaConcorrente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconaConcorrente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/icona_hyuna.png"))); // NOI18N
        pnlConcorrente1.add(lblIconaConcorrente1, java.awt.BorderLayout.CENTER);

        lblConcorrente1.setBackground(new java.awt.Color(153, 153, 255));
        lblConcorrente1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblConcorrente1.setForeground(new java.awt.Color(255, 255, 255));
        lblConcorrente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcorrente1.setText("nome 1");
        lblConcorrente1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlConcorrente1.add(lblConcorrente1, java.awt.BorderLayout.PAGE_START);

        pnlConcorrente2.setBackground(new java.awt.Color(51, 255, 255));
        pnlConcorrente2.setOpaque(false);
        pnlConcorrente2.setLayout(new java.awt.BorderLayout());

        lblIconaConcorrente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconaConcorrente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/icona_ivan.png"))); // NOI18N
        pnlConcorrente2.add(lblIconaConcorrente2, java.awt.BorderLayout.CENTER);

        lblConcorrente2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblConcorrente2.setForeground(new java.awt.Color(255, 255, 255));
        lblConcorrente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcorrente2.setText("nome 2");
        lblConcorrente2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlConcorrente2.add(lblConcorrente2, java.awt.BorderLayout.PAGE_START);

        pnlRound.setBackground(new java.awt.Color(51, 255, 255));
        pnlRound.setOpaque(false);
        pnlRound.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlStageLayout = new javax.swing.GroupLayout(pnlStage);
        pnlStage.setLayout(pnlStageLayout);
        pnlStageLayout.setHorizontalGroup(
            pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlConcorrente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlConcorrente2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRound, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStageLayout.setVerticalGroup(
            pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStageLayout.createSequentialGroup()
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStageLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlConcorrente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlConcorrente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlStageLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(pnlRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnlStage);
        pnlStage.setBounds(0, 50, 701, 370);

        pnlMenuSuperiore.setBackground(new java.awt.Color(51, 51, 51));

        lblNRound.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNRound.setForeground(new java.awt.Color(255, 255, 255));
        lblNRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNRound.setText("──── round - ────");

        btnMutaMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMutaMusica.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMutaMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMutaMusica.setText("🔇");
        btnMutaMusica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnMutaMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMutaMusica.setEnabled(false);
        btnMutaMusica.setFocusPainted(false);
        btnMutaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutaMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuSuperioreLayout = new javax.swing.GroupLayout(pnlMenuSuperiore);
        pnlMenuSuperiore.setLayout(pnlMenuSuperioreLayout);
        pnlMenuSuperioreLayout.setHorizontalGroup(
            pnlMenuSuperioreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSuperioreLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnMutaMusica)
                .addGap(27, 27, 27)
                .addComponent(lblNRound, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnlMenuSuperioreLayout.setVerticalGroup(
            pnlMenuSuperioreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSuperioreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuSuperioreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNRound)
                    .addComponent(btnMutaMusica))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenuSuperiore);
        pnlMenuSuperiore.setBounds(0, 0, 700, 50);

        lblSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/stage1.png"))); // NOI18N
        lblSfondo.setText("jLabel1");
        getContentPane().add(lblSfondo);
        lblSfondo.setBounds(0, 40, 700, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProssimoRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProssimoRoundActionPerformed
        if (musica != null) musica.stop();
        GestioneTorneo.getTorneo().registraVincitore(GestioneRound.getVincitoreRound());
        if(!GestioneRound.nuovoRound(pb1, pb2)){
            FrmVincitoreTorneo frmVincitore = new FrmVincitoreTorneo();
            frmVincitore.setVisible(true);
            this.dispose();
        }
        else{
            ScriviConcorrenti();
            pb1.setValue(0);
            pb2.setValue(0);
            btnAvviaRound.setEnabled(true);
            btnProssimoRound.setEnabled(false);
            btnMutaMusica.setEnabled(false);
            prossimoSfondo();
            if(GestioneRound.getNRound() == 5) btnProssimoRound.setText("VEDI VINCITORE");
        }
        scriviRound();
    }//GEN-LAST:event_btnProssimoRoundActionPerformed

    private void btnAvviaRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaRoundActionPerformed
        GestioneRound.avviaRound();
        musica = new MusicaSottofondo(GestioneMusica.cambiaCanzone());
        musica.start();
        if(musicaMutata)musica.setVolume(-80);
        else musica.setVolume(-20);

        btnAvviaRound.setEnabled(false);
        btnProssimoRound.setEnabled(false);
        btnMutaMusica.setEnabled(true);
        Thread t = new Thread(() -> {
            while (!GestioneRound.getRound().isFinito()) {
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {}
            }
            javax.swing.SwingUtilities.invokeLater(() -> {
                btnProssimoRound.setEnabled(true);               
                FrmVincitoreRound frmVincitoreRound = new FrmVincitoreRound();
                frmVincitoreRound.setVisible(true);
            });
        });
        t.start();
    }//GEN-LAST:event_btnAvviaRoundActionPerformed

    private void btnMutaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutaMusicaActionPerformed
        if(musicaMutata){
            musica.setVolume(-20);
            btnMutaMusica.setText("🔇");
            musicaMutata = false;
        }
        else{
            musica.setVolume(-80);
            btnMutaMusica.setText("🔊");
            musicaMutata = true;
        }
    }//GEN-LAST:event_btnMutaMusicaActionPerformed

    /**
     * Metodo che aggiorna il label round
     */
    public void scriviRound(){
        if(GestioneRound.getNRound() == 5){
            lblNRound.setText("──── Finale ────");
            lblNRound.setHorizontalAlignment(SwingConstants.CENTER);
        }
        else if(GestioneRound.getNRound() == 4){
            lblNRound.setText("──── Semi Finale ────");
            lblNRound.setHorizontalAlignment(SwingConstants.CENTER);
        }
        else if(GestioneRound.getNRound() < 4){
            lblNRound.setText("──── Round " + GestioneRound.getNRound() +" ────");
            lblNRound.setHorizontalAlignment(SwingConstants.CENTER);
        } 
    }
    
    /**
     * Metodo che aggiorna i componenti in base ai concorrenti
     */
    public void ScriviConcorrenti(){
        lblConcorrente1.setText(GestioneRound.getConcorrentiAttuali()[0].getNome());
        lblConcorrente1.setHorizontalAlignment(SwingConstants.CENTER);
        lblConcorrente2.setText(GestioneRound.getConcorrentiAttuali()[1].getNome());
        lblConcorrente2.setHorizontalAlignment(SwingConstants.CENTER);
        pb1.setForeground(GestioneRound.getConcorrentiAttuali()[0].getColore());
        pb2.setForeground(GestioneRound.getConcorrentiAttuali()[1].getColore());
        lblIconaConcorrente1.setIcon(GestioneRound.getConcorrentiAttuali()[0].getIcona());
        lblIconaConcorrente2.setIcon(GestioneRound.getConcorrentiAttuali()[1].getIcona());
    }
    
    /**
     * Metodo per inizializzare gli sfondi
     * @return lista con gli sfondi
     */
    public ArrayList<ImageIcon> getListaSfondi(){
        ArrayList<ImageIcon> sfondi = new ArrayList<>();
        sfondi.add(new ImageIcon(getClass().getResource("/immagini/stage1.png")));
        sfondi.add(new ImageIcon(getClass().getResource("/immagini/stage2.png")));
        sfondi.add(new ImageIcon(getClass().getResource("/immagini/stage3.png")));
        sfondi.add(new ImageIcon(getClass().getResource("/immagini/stage4.png")));
        sfondi.add(new ImageIcon(getClass().getResource("/immagini/stage5.png")));
        Collections.shuffle(sfondi);
        return sfondi;
    }
    
    /**
     * Metodo per passare allo sfondo successivo
     */
    public void prossimoSfondo(){
        lblSfondo.setIcon(sfondi.poll());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmStage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvviaRound;
    private javax.swing.JButton btnMutaMusica;
    private javax.swing.JButton btnProssimoRound;
    private javax.swing.JLabel lblConcorrente1;
    private javax.swing.JLabel lblConcorrente2;
    private javax.swing.JLabel lblIconaConcorrente1;
    private javax.swing.JLabel lblIconaConcorrente2;
    private javax.swing.JLabel lblNRound;
    private javax.swing.JLabel lblSfondo;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JPanel pnlConcorrente1;
    private javax.swing.JPanel pnlConcorrente2;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuSuperiore;
    private javax.swing.JPanel pnlRound;
    private javax.swing.JPanel pnlStage;
    // End of variables declaration//GEN-END:variables
}
