/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aureligiuliagarathread;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author aureli.giulia
 */
public class FrmVincitore extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVincitore.class.getName());
    private MusicaSottofondo musica;
    private boolean musicaMutata;
    /**
     * Creates new form FrmVincitore
     */
    public FrmVincitore() {
        initComponents();
        // Imposta il messaggio finale nel JLabel
        String vincitore = GestioneRound.getVincitoreRound().toString();
        Color coloreCampione = GestioneTorneo.getTorneo().getCampione().getColore();
        String coloreHex = String.format("#%02x%02x%02x", coloreCampione.getRed(), coloreCampione.getGreen(), coloreCampione.getBlue());
        String testoFinale = "<html>"
        + "<div style='text-align:center;'>"
        + "<span style='font-size:18px; color:white;'><b>🏆 Torneo finito! 🏆</b></span><br><br>"
        + "<span style='font-size:18px; color:white;'>Il campione finale è:</span><br>"
        + "<span style='font-size:26px; color:" + coloreHex + ";'><b>" + vincitore + "</b></span>"
        + "</div>"
        + "</html>";
        // Assegna al JLabel
        lblRisultato.setText(testoFinale);
        lblRisultato.setHorizontalAlignment(SwingConstants.CENTER);
        lblIconaCampione.setIcon(GestioneTorneo.getTorneo().getCampione().getIconaTesta());
        musica = new MusicaSottofondo("/suoni/Karma.wav");
        musica.start();
        musica.setVolume(-20);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCampione = new javax.swing.JPanel();
        lblIconaCampione = new javax.swing.JLabel();
        lblRisultato = new javax.swing.JLabel();
        btnRitornoSchermataIniziale = new javax.swing.JButton();
        btnMutaMusica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCampione.setBackground(new java.awt.Color(102, 102, 102));

        lblIconaCampione.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/icona_testa_hyuna.png"))); // NOI18N
        lblIconaCampione.setText("jLabel1");

        lblRisultato.setText("lblRisultato");

        btnRitornoSchermataIniziale.setBackground(new java.awt.Color(0, 0, 0));
        btnRitornoSchermataIniziale.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRitornoSchermataIniziale.setForeground(new java.awt.Color(255, 255, 255));
        btnRitornoSchermataIniziale.setText("TORNA ALLA SCHERMATA INIZIALE ");
        btnRitornoSchermataIniziale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnRitornoSchermataIniziale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRitornoSchermataIniziale.setFocusPainted(false);
        btnRitornoSchermataIniziale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRitornoSchermataInizialeActionPerformed(evt);
            }
        });

        btnMutaMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMutaMusica.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMutaMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMutaMusica.setText("🔇");
        btnMutaMusica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        btnMutaMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMutaMusica.setFocusPainted(false);
        btnMutaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutaMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCampioneLayout = new javax.swing.GroupLayout(pnlCampione);
        pnlCampione.setLayout(pnlCampioneLayout);
        pnlCampioneLayout.setHorizontalGroup(
            pnlCampioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCampioneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconaCampione, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(pnlCampioneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCampioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCampioneLayout.createSequentialGroup()
                        .addComponent(btnMutaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnRitornoSchermataIniziale, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(pnlCampioneLayout.createSequentialGroup()
                        .addComponent(lblRisultato, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCampioneLayout.setVerticalGroup(
            pnlCampioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCampioneLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblRisultato)
                .addGap(49, 49, 49)
                .addComponent(lblIconaCampione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(pnlCampioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRitornoSchermataIniziale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMutaMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCampione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCampione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRitornoSchermataInizialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRitornoSchermataInizialeActionPerformed
        if (musica != null) musica.stop();
        FrmSchermataIniziale frmSchermataIniziale = new FrmSchermataIniziale();
        frmSchermataIniziale.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRitornoSchermataInizialeActionPerformed

    private void btnMutaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutaMusicaActionPerformed
        if(musicaMutata){
            musica.setVolume(-20);
            btnMutaMusica.setText("🔇");
            musicaMutata = false;
        }
        else{
            musica.setVolume(-80);
            btnMutaMusica.setText("🔊");
            musicaMutata = true;
        }
    }//GEN-LAST:event_btnMutaMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVincitore().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMutaMusica;
    private javax.swing.JButton btnRitornoSchermataIniziale;
    private javax.swing.JLabel lblIconaCampione;
    private javax.swing.JLabel lblRisultato;
    private javax.swing.JPanel pnlCampione;
    // End of variables declaration//GEN-END:variables
}
